CREATE TABLE NETFLIX(
SHOW_ID VARCHAR(20),
TYPE VARCHAR(10),
TITLE VARCHAR(150),
DIRECTOR VARCHAR(250),
CASTS VARCHAR(1500),
COUNTRY VARCHAR(150),
DATE_ADDED VARCHAR(150),
RELEASE_YEAR INT,
RATING VARCHAR(50),
DURATION VARCHAR(50),
LISTED_IN VARCHAR(100),
DESCRIPTION VARCHAR(250)
)
SELECT TYPE, COUNT(*) AS TOTAL_COUNT
FROM NETFLIX
GROUP BY TYPE

SELECT TYPE , RATING FROM(
SELECT TYPE, RATING , COUNT(*) , RANK() OVER(PARTITION BY TYPE ORDER BY COUNT(*) DESC ) AS RANK FROM NETFLIX
GROUP BY TYPE,RATING) 
AS TABLE_1
WHERE RANK = 1

SELECT * FROM NETFLIX

SELECT * FROM NETFLIX
WHERE TYPE = 'Movie' AND RELEASE_YEAR = 2020

SELECT DISTINCT(UNNEST(STRING_TO_ARRAY(COUNTRY,','))),COUNT(SHOW_ID) AS CONTENT FROM NETFLIX
WHERE country IS NOT NULL
GROUP BY COUNTRY 
ORDER BY CONTENT DESC LIMIT 5

SELECT * FROM NETFLIX 
WHERE TYPE = 'Movie'
AND 
DURATION = (SELECT MAX(DURATION) FROM NETFLIX)

SELECT * FROM NETFLIX
WHERE TO_DATE(DATE_ADDED ,'MONTH DD,YYYY') >=CURRENT_DATE - INTERVAL '5 YEARS'

SELECT * FROM NETFLIX
WHERE DIRECTOR LIKE '%Rajiv Chilaka%'

SELECT * FROM  NETFLIX
WHERE TYPE = 'TV Show'
AND 
SPLIT_PART(DURATION , ' ',1)::NUMERIC > 5

SELECT COUNT(*), UNNEST(STRING_TO_ARRAY(LISTED_IN,',')) AS GENRE FROM NETFLIX
GROUP BY UNNEST(STRING_TO_ARRAY(LISTED_IN,','))

SELECT EXTRACT(YEAR FROM TO_DATE(DATE_ADDED ,'MONTH DD, YYYY')) as year, COUNT(*) YEAR_WISE_CONTENT,
ROUND(count(*):: numeric /(select count(*) FROM NETFLIX WHERE COUNTRY = 'India')::numeric *100,2) as AVG_CONTENT
from NETFLIX
WHERE COUNTRY = 'India'
group by 1

SELECT * FROM netflix
WHERE listed_in ILIKE '%documentaries%'

SELECT * FROM netflix
WHERE DIRECTOR IS NULL

SELECT * FROM NETFLIX 
WHERE CASTS ILIKE '%SALMAN KHAN%'
AND 
RELEASE_YEAR > EXTRACT(YEAR FROM CURRENT_DATE - INTERVAL '10 YEARS')

SELECT UNNEST(STRING_TO_ARRAY(CASTS,',')) AS HERO , COUNT(*) AS TOTAL_MOVIES FROM NETFLIX
WHERE COUNTRY ILIKE '%INDIA'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10


WITH CATEGORY_TABLE AS
(SELECT *, 
CASE
WHEN DESCRIPTION ILIKE '%KILL%'OR DESCRIPTION ILIKE '%VOILENT%' THEN 'BAD_MOVIE' 
ELSE 'GOOD MOVIE'
END AS MOVIE_CATEGORY 
FROM NETFLIX)
SELECT MOVIE_CATEGORY , COUNT(*) AS TOTAL FROM CATEGORY_TABLE
GROUP BY  MOVIE_CATEGORY 
